---
rgbank:
  production:
    components:
      Rgbank::Web:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"production\" and
          facts.trusted.extensions.pp_apptier = \"web\" }"
      Rgbank::Db:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"production\" and
          facts.trusted.extensions.pp_apptier = \"database\" }"
      Rgbank::Load:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"production\" and
          facts.trusted.extensions.pp_apptier = \"loadbalancer\" }"
  staging:
    parameters:
      db_username: 'staginguser'
      db_password: 'myawesomepassword'
    components:
      Rgbank::Web:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"staging\" and
          facts.trusted.extensions.pp_apptier = \"web\" }"
      Rgbank::Db:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"staging\" and
          facts.trusted.extensions.pp_apptier = \"database\" }"
      Rgbank::Load:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"staging\" and
          facts.trusted.extensions.pp_apptier = \"loadbalancer\" }"
  dev:
    parameters:
      listen_port: 80
    components:
      Rgbank::Web:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"development\" and
          facts.trusted.extensions.pp_apptier = \"all\" and
          nodes { deactivated is null } }"
      Rgbank::Db: 
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"development\" and
          facts.trusted.extensions.pp_apptier = \"all\" and
          nodes { deactivated is null } }"
