---
rgbank:
  dev_aws:
    components:
      Rgbank::Web:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"development\" and
          facts.trusted.extensions.pp_apptier = \"all\" and
          nodes { deactivated is null } }"
      Rgbank::Db:
        query: "inventory[certname] {
          facts.trusted.extensions.pp_application = \"rgbank\" and
          facts.trusted.extensions.pp_environment = \"development\" and
          facts.trusted.extensions.pp_apptier = \"all\" and
          nodes { deactivated is null } }"

